In [195]:
import numpy as np
import pandas as pd
import tensorflow as tf


In [196]:
dataset=pd.read_csv("/content/Dataset_master - American Express User Exit Pred.csv")
X=dataset.iloc[:,0:-1].values
y=dataset.iloc[:,-1].values

In [197]:
print(X)

[[553 'Delhi' 'Female' ... 4 1 274150]
 [447 'Bengaluru' 'Male' ... 4 1 519360]
 [501 'Delhi' 'Female' ... 4 1 545501]
 ...
 [627 'Mumbai' 'Female' ... 4 0 494067]
 [600 'Bengaluru' 'Female' ... 2 1 109375]
 [553 'Delhi' 'Male' ... 4 1 180031]]


In [198]:
from sklearn.preprocessing import LabelEncoder
label_encoder=LabelEncoder()
X[:,2]=label_encoder.fit_transform(X[:,2])

In [199]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X=np.array(ct.fit_transform(X))


In [200]:
print(X)

[[0.0 1.0 0.0 ... 4 1 274150]
 [1.0 0.0 0.0 ... 4 1 519360]
 [0.0 1.0 0.0 ... 4 1 545501]
 ...
 [0.0 0.0 1.0 ... 4 0 494067]
 [1.0 0.0 0.0 ... 2 1 109375]
 [0.0 1.0 0.0 ... 4 1 180031]]


In [201]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state= 0)

In [202]:
X

array([[0.0, 1.0, 0.0, ..., 4, 1, 274150],
       [1.0, 0.0, 0.0, ..., 4, 1, 519360],
       [0.0, 1.0, 0.0, ..., 4, 1, 545501],
       ...,
       [0.0, 0.0, 1.0, ..., 4, 0, 494067],
       [1.0, 0.0, 0.0, ..., 2, 1, 109375],
       [0.0, 1.0, 0.0, ..., 4, 1, 180031]], dtype=object)

In [203]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train = sc.fit_transform(X_train)
X_test= sc.transform(X_test)


In [204]:
ann=tf.keras.models.Sequential()

In [226]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [227]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [228]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [233]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [235]:
ann.fit(X_train,y_train,batch_size=32,epochs=120)

Epoch 1/120
249/249 [==============================] - 2s 3ms/step - loss: 0.5555 - accuracy: 0.7858
Epoch 2/120
249/249 [==============================] - 1s 3ms/step - loss: 0.4027 - accuracy: 0.8483
Epoch 3/120
249/249 [==============================] - 1s 3ms/step - loss: 0.3710 - accuracy: 0.8486
Epoch 4/120
249/249 [==============================] - 0s 2ms/step - loss: 0.3660 - accuracy: 0.8474
Epoch 5/120
249/249 [==============================] - 1s 2ms/step - loss: 0.3644 - accuracy: 0.8464
Epoch 6/120
249/249 [==============================] - 1s 2ms/step - loss: 0.3625 - accuracy: 0.8488
Epoch 7/120
249/249 [==============================] - 0s 2ms/step - loss: 0.3625 - accuracy: 0.8508
Epoch 8/120
249/249 [==============================] - 0s 2ms/step - loss: 0.3636 - accuracy: 0.8483
Epoch 9/120
249/249 [==============================] - 0s 2ms/step - loss: 0.3619 - accuracy: 0.8509
Epoch 10/120
249/249 [==============================] - 0s 2ms/step - loss: 0.3611 - accura

In [236]:
print(ann.predict(sc.transform([[0.0,1.0,0.0,501,0,32,2,0.0,4,1,545501]]))>0.5)

1/1 [==============================] - 0s 83ms/step
[[False]]


In [237]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>0.5)


63/63 [==============================] - 0s 1ms/step


In [238]:
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[0 1]
 [0 0]
 [0 0]
 ...
 [0 1]
 [0 0]
 [0 1]]


In [239]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)
accuracy_score(y_test,y_pred)

[[1505   68]
 [ 227  186]]


0.851460221550856